# Generated by Django 4.2.6 on 2023-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('director_name', models.CharField(max_length=200)),
                ('writers_name', models.CharField(max_length=250)),
                ('tagline', models.CharField(max_length=350)),
                ('created_date', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('subject', models.TextField()),
                ('reviews', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='TopCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('actor_name', models.CharField(max_length=200)),
                ('character_name', models.CharField(max_length=200)),
            ],
        ),
    ]
